- name: hello world
  hosts: all
  tasks: 
    - name: print Hello World
      ansible.builtin.debug:
         msg: Hwllo World

    - name: Incllude Hello Universal
      ansible.builtin.include_tasks:
        file: universal.yml